"""Freeze the verified environment and check the deployment Python compatibility."""
from importlib.metadata import distribution, distributions
from pathlib import Path
from packaging.requirements import Requirement
from packaging.specifiers import SpecifierSet
from packaging.markers import default_environment

root = Path(__file__).resolve().parents[1] / "server"
env = default_environment()
env.update(python_version="3.11", python_full_version="3.11.9", sys_platform="linux", os_name="posix", platform_system="Linux", extra="")
seen = {}


def visit(name):
    dist = distribution(name)
    canonical = dist.metadata["Name"]
    if canonical in seen:
        return
    requires_python = dist.metadata.get("Requires-Python", "")
    assert SpecifierSet(requires_python).contains("3.11.9"), (canonical, requires_python)
    seen[canonical] = dist.version
    for value in dist.requires or []:
        req = Requirement(value)
        if req.marker is None or req.marker.evaluate(env):
            visit(req.name)


for name in root.joinpath("requirements.in").read_text().splitlines():
    if name.strip():
        visit(name.strip())
header = "# Verified versions; generated by scripts/lock_server.py. Python 3.11.\n"
root.joinpath("requirements.txt").write_text(header + "".join(f"{n}=={v}\n" for n, v in sorted(seen.items(), key=lambda x: x[0].lower())), encoding="utf-8")
for name in ("pytest", "httpx"):
    visit(name)
root.joinpath("requirements-dev.txt").write_text(header + "".join(f"{n}=={v}\n" for n, v in sorted(seen.items(), key=lambda x: x[0].lower())) + "colorama==0.4.6; sys_platform == 'win32'\n", encoding="utf-8")
print("Locked production and test dependencies; all declare Python 3.11 compatibility.")
